### ISSUE TITLE
Any idea

### ISSUE THREAD

**Issue by focus85** [altdesktop/i3ipc-python#133]
I keep getting the following error any advice

'Con' object has no attribute 'props'
Traceback (most recent call last):
  File "./sane_i3.py", line 76, in <module>
    i3.main()
  File "/usr/lib/python3.7/site-packages/i3ipc/connection.py", line 518,
    raise loop_exception
  File "/usr/lib/python3.7/site-packages/i3ipc/connection.py", line 497,
    while not self._event_socket_poll():
  File "/usr/lib/python3.7/site-packages/i3ipc/connection.py", line 477,
    raise e
  File "/usr/lib/python3.7/site-packages/i3ipc/connection.py", line 474,
    self._pubsub.emit(event_name, event)
  File "/usr/lib/python3.7/site-packages/i3ipc/_private/pubsub.py", line
    s['handler'](self.conn, data)
  File "./sane_i3.py", line 24, in on_window_new
    if e.container.props.floating == "user_on":
AttributeError: 'Con' object has no attribute 'props'

**Comment by acrisci** [comment]
Yeah you should just access the properties directly and that works with all the versions. I removed all the props object usage from the examples.

**Comment by focus85** [comment]
yes, that's fix the issue. Thank you.
